/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/components/AdminCard': RouteRecordInfo<'/admin/components/AdminCard', '/admin/components/AdminCard', Record<never, never>, Record<never, never>>,
    '/admin/components/AdminChatDialog': RouteRecordInfo<'/admin/components/AdminChatDialog', '/admin/components/AdminChatDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/ClaimItemDialog': RouteRecordInfo<'/admin/components/ClaimItemDialog', '/admin/components/ClaimItemDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/ConvoDialog': RouteRecordInfo<'/admin/components/ConvoDialog', '/admin/components/ConvoDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/DashboardItemCards': RouteRecordInfo<'/admin/components/DashboardItemCards', '/admin/components/DashboardItemCards', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/components/dialogs/AdminUserRolesDialog', '/admin/components/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/ItemCard': RouteRecordInfo<'/admin/components/ItemCard', '/admin/components/ItemCard', Record<never, never>, Record<never, never>>,
    '/admin/components/NotifDialog': RouteRecordInfo<'/admin/components/NotifDialog', '/admin/components/NotifDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/PostItemDialog': RouteRecordInfo<'/admin/components/PostItemDialog', '/admin/components/PostItemDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/RecentActivity': RouteRecordInfo<'/admin/components/RecentActivity', '/admin/components/RecentActivity', Record<never, never>, Record<never, never>>,
    '/admin/components/SearchBar': RouteRecordInfo<'/admin/components/SearchBar', '/admin/components/SearchBar', Record<never, never>, Record<never, never>>,
    '/admin/components/StatsCards': RouteRecordInfo<'/admin/components/StatsCards', '/admin/components/StatsCards', Record<never, never>, Record<never, never>>,
    '/admin/components/Summary': RouteRecordInfo<'/admin/components/Summary', '/admin/components/Summary', Record<never, never>, Record<never, never>>,
    '/admin/components/SystemStats': RouteRecordInfo<'/admin/components/SystemStats', '/admin/components/SystemStats', Record<never, never>, Record<never, never>>,
    '/admin/components/userChatDialog': RouteRecordInfo<'/admin/components/userChatDialog', '/admin/components/userChatDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/UsersTable': RouteRecordInfo<'/admin/components/UsersTable', '/admin/components/UsersTable', Record<never, never>, Record<never, never>>,
    '/admin/DashboardView': RouteRecordInfo<'/admin/DashboardView', '/admin/DashboardView', Record<never, never>, Record<never, never>>,
    '/admin/RolePagesView': RouteRecordInfo<'/admin/RolePagesView', '/admin/RolePagesView', Record<never, never>, Record<never, never>>,
    '/admin/UserManagement': RouteRecordInfo<'/admin/UserManagement', '/admin/UserManagement', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/ProfilesView': RouteRecordInfo<'/ProfilesView', '/ProfilesView', Record<never, never>, Record<never, never>>,
  }
}
